# Generated by Django 5.2.8 on 2025-11-17 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono (nombre)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('product_type', models.CharField(choices=[('sale', 'Venta'), ('exchange', 'Intercambio'), ('both', 'Venta/Intercambio')], default='sale', max_length=10, verbose_name='Tipo')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('like_new', 'Como nuevo'), ('good', 'Buen estado'), ('fair', 'Estado aceptable')], default='new', max_length=10, verbose_name='Condición')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('inactive', 'Inactivo')], default='available', max_length=10, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Tamaño/Volumen')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('views', models.IntegerField(default=0, verbose_name='Visualizaciones')),
                ('favorites_count', models.IntegerField(default=0, verbose_name='Favoritos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_offers', to='products.product', verbose_name='Producto ofrecido')),
                ('requested_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='products.product', verbose_name='Producto solicitado')),
            ],
            options={
                'verbose_name': 'Solicitud de Intercambio',
                'verbose_name_plural': 'Solicitudes de Intercambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='products.product', verbose_name='Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Visualización',
                'verbose_name_plural': 'Visualizaciones',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_at'], name='products_pr_status_36c7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='products_pr_seller__2449b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
    ]
