# Generated by Django 5.2.8 on 2025-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sale', 'Venta')], default='sale', max_length=10, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='ExchangeRequest',
        ),
    ]
