# Generated by Django 5.2.8 on 2025-12-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('exchange', 'Intercambio'), ('both', 'Venta/Intercambio')], default='sale', max_length=10, verbose_name='Tipo'),
        ),
    ]
